### ISSUE TITLE
Blank pages

### ISSUE THREAD

**Issue by macra** [technofreaky/woocomerce-quick-donation#56]
Updated to the latest version, and am getting blank pages in a number of places. When trashing donations from the donation listing, when restoring donations from the trash, after saving setting changes.

**Comment by macra** [comment]
Ok I just noticed that the plugin is causing a blank page to load even with regular wordpress page updates etc.
Not good :( Had to disable the plugin

**Comment by macra** [comment]
It's trying to redirect to wp-admin/options.php

**Comment by macra** [comment]
Looks like its stripping the the query string from the redirct url

**Comment by technofreaky** [comment]
Can you please tell the steps reproduce this issue ?

On Mon, Nov 09, 2015 at 3:48 am, Craig Macdonald < notifications@github.com [notifications@github.com] > wrote:
Looks like its stripping the the query string from the redirct url

—
Reply to this email directly or view it on GitHub
[https://github.com/technofreaky/woocomerce-quick-donation/issues/56#issuecomment-154881442] .[https://github.com/notifications/beacon/ABzAf3ug00x6r1NOHsR3DZkmW_U4MvOsks5pD8GkgaJpZM4GeP2W.gif]

**Comment by technofreaky** [comment]
@macra if possible can you come on live chat ? 
Chat Link : https://www.hipchat.com/gVcsNs3aC

**Comment by macra** [comment]
Hi Varun, due to being in New Zealand, it's tricky to get the timing right when we are both online. I'll try to catch up when our times overlap favorably.  I'll clone the current site back into development mode, due to the sensitive nature of some of the content on the actual website, for security reasons I'm unable to give access. I'll let you know when I have a dev version available for you to check. Thanks for your excellent support.

**Comment by technofreaky** [comment]
hi,

in the latest version 1.2.7 the issue has been fixed.

kindly check with the latest version

**Comment by kkotha82** [comment]
@macra I had the same issue.. Go to <b>../plugins/woocommerce-quick-donation/includes/admin/settings/fields.php</b> and remove the <b>?></b> PHP closing tag on line 132. That solved the issue for me. This is a quick fix for now. See if it helps.

**Comment by kkotha82** [comment]
@technofreaky I had the same problem with blank pages while performing admin actions on different pages. I turned on WP DEBUG and I saw two errors:

Warning: Cannot modify header information - headers already sent by (output started at ../wp-content/plugins/woocommerce-quick-donation/includes/admin/settings/fields.php:132) in ../wp-includes/option.php on line 787

Warning: Cannot modify header information - headers already sent by (output started at ../wp-content/plugins/woocommerce-quick-donation/includes/admin/settings/fields.php:132) in ../wp-includes/option.php on line 788

I removed the PHP closing tag <b>?></b> on line 132 of fields.php in the plugin, and it resolved the issue. You might want to look into what exactly is causing this issue.

**Comment by macra** [comment]
@kkotha82 Worked for me, thanks friend.

**Comment by Blackhawke** [comment]
I just installed the plugin today and am still having the issue (blank page on save) -- though at this point it seems to be limited to pages/actions associated with the plugin. If that changes, I'll let you know. I'm about to go work on (Yada) Wiki pages, so whether or not it has created the blank page problem system wide will soon be apparent. (If it has, I'll have to disable the plugin until it's fixed. I can't have the plugin destabilizing the site.)

(Also, why does the "configure payment gateway" warning show up even after the payment gateways have been set? Worrying! (While we're at it, why not have the plugin pull the default payment gateways from the Woocommerce system settings? Then, if the user wants to choose a different gateway for their donations, they can do that. That might be a better use for the warning banner.)

**Comment by kkotha82** [comment]
@macra Glad to know!

**Comment by Blackhawke** [comment]
As you noticed in the other bug report I filed, I had to disable the plugin because of the media library bug, so I never got a chance to see if the blank page problem persisted throughout the system.
